spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: diploma

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234

  liquibase:
    change-log: classpath:db/changelog/changelog.yml

  session:
    jdbc:
      initialize-schema: always
      table-name: spring_session
    timeout: 2592000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: urazov.buj@gmail.com
    password: nqcclfcskzydhdkp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true