<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Личный кабинет</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/css/account.css">
</head>
<body>
    <header class="header">
        <div class="header__logo">
            <img src="logo.png" alt="Логотип">
        </div>
        <nav class="header__nav">
            <ul class="nav">

            </ul>
        </nav>
        <a href="/logout" class="header__action">Выход</a>
    </header>
    <i id="theme-toggle" class="fa-solid fa-moon"></i>
</body>
<script src="/scripts/account.js"></script>
</html>