<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/css/taskOpen.css">
    <title>Document</title>
</head>
<body>
    <form class="main" action="/open" method="post">
        <a class="back" href="/"><i class="fa-solid fa-arrow-left"></i> Главная</a>
        <h2>Присоединитесь к заданию</h2>
        <div class="input-group">
            <input type="text" name="code" placeholder="Введите код задания">
            <input type="submit" value="Открыть">
        </div>
    </form>
</body>
</html>